import Head from 'next/head';
import { POSTS } from '../graphql/queries';
import { client } from '../graphql/graphqlClient';
import BlogPosts from '../components/BlogPosts';

export async function getStaticProps() {
  let data;

  try {
    data = await client.query({ query: POSTS });
  }
  catch (err) {
    console.log('ERROR', err);
  }

  return {
    props: {
      posts: data.data.posts
    },
    revalidate: 60
  };
}

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>MC Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BlogPosts posts={posts} />
      </main>
    </div>
  )
}
